inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: def

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/dummy/db/schema.rb

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - node_modules/**/*
