sudo: false
cache: bundler
rvm:
  - 2.5.1
addons:
  chrome: stable
before_install:
  - gem install bundler
  - yarn install
before_script:
  - ln -s spec/dummy/node_modules node_modules
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
