sudo: false
cache: bundler
rvm:
  - 2.5.1
addons:
  chrome: stable
env:
  global:
    - TRAVIS=true
    - DISPLAY=:99.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - gem install bundler
  - bundle exec rails webpacker:compile
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
